### ISSUE TITLE
Suggestion/Request: Add image number.

### ISSUE THREAD

**Issue by MistakingManx** [Meeken1998/furazy-spider#1]
I don't know if this is already a feature or not, but I'd like to be able to randomize the image number from the page..I am probably explaining this horrible.

You can choose the page, can you make it so there is an option to choose a randomized image from that page instead of just the first one?

**Comment by Meeken1998** [comment]
Thank u for yr suggestion~In fact, I planned to develop this function before, and I will add it soon. :3
